version: '3.8'

services:
  partners-db:
    env_file: .env
    image: postgres:12.17
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    restart: always
    volumes:
      - partners_volume:/var/lib/postgresql/data
    networks:
      - partners-net

  partners-server:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      DB_HOST: ${DB_HOST}
      DATABASE_URL: postgresql://myuser:mypassword@partners-db:5432/prisma?schema=public
    depends_on:
      - partners-db
    networks:
      - partners-net

networks:
  partners-net:
    driver: bridge

volumes:
  partners_volume:
